import os
from dotenv import load_dotenv

load_dotenv()

DB_URI = os.getenv("DB_URI")
DEV_DB_URI = os.getenv("DEV_DB_URI")
CONFIG_NAME = os.getenv("CONFIG_NAME")
SECRET_KEY = os.getenv("SECRET_KEY")
REDIS_URL = os.getenv("REDIS_URL")
EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
FROM_EMAIL = os.getenv("FROM_EMAIL")
CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")
MAINTENANCE_MODE = int(os.getenv("MAINTENANCE_MODE"))
REDIS_EXPIRE = int(os.getenv("REDIS_EXPIRE"))
FILE_NAME = os.getenv("FILE_NAME")
RATE_LIMIT = int(os.getenv("RATE_LIMIT"))
WINDOW_SECONDS = int(os.getenv("WINDOW_SECONDS"))
PAYSTACK_SECRET = os.environ.get("PAYSTACK_SECRET")
CLOUDINARY_UPLOAD_FOLDER = os.getenv("CLOUDINARY_UPLOAD_FOLDER")
PAYSTACK_PUBLIC_KEY = os.getenv("PAYSTACK_PUBLIC_KEY")
