services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    container_name: RealEstateApi
    depends_on:
      - redis
    networks:
      - RealNetwork
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./static/uploads:/app/static/uploads

  redis:
    image: redis
    container_name: RealEstateRedis
    networks:
      - RealNetwork
    ports:
      - 127.0.0.1:6380:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    restart: always
    container_name: RealEstateCelery
    depends_on:
      - redis
    networks:
      - RealNetwork
    env_file:
      - .env
    volumes:
      - ./static/uploads:/app/static/uploads

networks:
  RealNetwork:
    driver: bridge